'use strict';
/* generated by gulpfile.js */
export default () => {
  return [
    '<input>',
    'alwaysShowCalendars',
    'applyButtonClasses',
    'autoApply',
    'autoUpdateInput',
    'buttonClasses',
    'cancelButtonClasses',
    'drops',
    'endDate',
    'isCustomDate',
    'isInvalidDate',
    'linkedCalendars',
    'locale',
    'maxDate',
    'maxSpan',
    'maxYear',
    'minDate',
    'minYear',
    'moment',
    'opens',
    'parentEl',
    'ranges',
    'showCustomRangeLabel',
    'showDropdowns',
    'showISOWeekNumbers',
    'showWeekNumbers',
    'singleDatePicker',
    'startDate',
    'template',
    'timePicker',
    'timePicker24Hour',
    'timePickerIncrement',
    'timePickerSeconds'
  ];
};
